table 'Dim Region'
	lineageTag: daf8449e-7cc7-51f6-86d2-199de55d1e6f

	column region_code
		dataType: string
		lineageTag: d5fdd543-1464-50d7-ac98-7226f45e1a7c
		summarizeBy: none
		sourceColumn: region_code

		annotation SummarizationSetBy = Automatic

	column region_name
		dataType: string
		lineageTag: 629df3a9-db71-5727-b821-9e4a2bbdbe9e
		summarizeBy: none
		sourceColumn: region_name
		sortByColumn: sort_order

		annotation SummarizationSetBy = Automatic

	column sort_order
		dataType: int64
		formatString: 0
		lineageTag: 34e1af00-947a-549b-ad94-17a318bd7c9a
		summarizeBy: none
		sourceColumn: sort_order

		annotation SummarizationSetBy = Automatic

	column is_core
		dataType: int64
		formatString: #,0
		lineageTag: a1a59600-c0d1-518e-874b-7d456e97fa73
		summarizeBy: none
		sourceColumn: is_core

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 07dcab35-1fac-5aea-a2e8-dd7ce21a895d
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	partition 'Dim Region' = m
		mode: import
		source =
				let
				    Source = GcdcTable("pbi_dim_region"),
				    Typed = Table.TransformColumnTypes(Source, {
				        {"region_code", type text},
				        {"region_name", type text},
				        {"sort_order", Int64.Type},
				        {"is_core", Int64.Type},
				        {"state", type text}
				    }, "en-AU")
				in
				    Typed

	annotation PBI_ResultType = Table
